In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
B = np.array([[7,8,10],[4,5,6],[1,2,3]])

In [5]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [6]:
C = A + B
C

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [7]:
E = A-B
E

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

In [8]:
np.sum(A)

46

In [9]:
np.sum(B, axis = 1)

array([25, 15,  6])

In [10]:
np.sum(C, axis = 0)

array([24, 30, 38])

In [11]:
D = A@B
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [14]:
E = np.sort(C, axis=None).reshape(3,3)
E

array([[ 8,  8,  8],
       [10, 10, 10],
       [12, 13, 13]])

In [15]:
E.T

array([[ 8, 10, 12],
       [ 8, 10, 13],
       [ 8, 10, 13]])