In [1]:
import numpy as np

In [2]:
sample = np.arange(100).reshape(5,-1)

In [5]:
answer = sample[:,:4]

In [6]:
print(answer)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
