In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = {
    'x1':[4,2,1,3,1,6],
    'x2':[1,8,0,2,4,7],
    'y':[2,-14,1,-1,-7,-8]
}

In [3]:
df = pd.DataFrame(data)
df

x1  x2   y
0   4   1   2
1   2   8 -14
2   1   0   1
3   3   2  -1
4   1   4  -7
5   6   7  -8

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def forwardprop(data, param):
    y = []
    temp =0
    X = data.to_numpy()
    b = param[-1]
    W = param[:-1]
    Y = X@ (W.T) + b
    Z = sigmoid(Y)
    return Z

In [6]:
def grad_descent(data, param, y_pred,erros, show_cost =False):
    y_act = data.iloc[:,-1].to_numpy()
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    err = -1*np.sum(((y_act*np.log(y_pred))+(1-y_act)*np.log(1-y_pred))) / len(y_act)
    erros.append(err)
    if show_cost:
        print("error: ", err)
    grads = []
    temp = (y_pred-y_act)
    for i in data.iloc[:,:-1].columns:
        X = data[i]
        dJ_dw = np.dot(temp, X)/len(y_act)
        grads.append(dJ_dw)
    dJ_db = np.sum((temp))/len(y_act)
    grads.append(dJ_db)
    return np.array(grads)

In [7]:
def backprop(data, param, grads, lr= 0.01):
    param = param- lr *grads
    return param

In [8]:
def model(df, epochs, learn =0.01, shcost =False):
    params =[]
    errors = []
    for i in df.iloc[:,:-1].columns:
        params.append(np.random.rand())
    params.append(np.random.rand())
    params = np.array(params)
    for i in range(epochs):
        Y_pred = forwardprop(df.iloc[:,:-1], params)
        grads = grad_descent(df, params, Y_pred,errors,   show_cost =shcost)
        params = backprop(df, params, grads, lr =learn)
        print(params)
    return params, errors

In [9]:
params, errors = model(df, 4500, learn =0.01, shcost =True)

error:  15.224483690918015
[-0.04236978 -0.04677827  0.29266438]
error:  -0.05722645235723086
[-0.1843613  -0.39058516  0.24266123]
error:  -13.762563002492277
[-0.31744992 -0.72059685  0.19548833]
error:  -26.57631184109684
[-0.44811236 -1.04818941  0.14921774]
error:  -39.20877723072925
[-0.57777728 -1.37515732  0.10332372]
error:  -51.783956910478054
[-0.70699626 -1.70192728  0.05761453]
error:  -64.33740859448996
[-0.83599875 -2.02863064  0.01201586]
error:  -76.8815184593182
[-0.96487879 -2.35531072 -0.03350273]
error:  -89.42083343723193
[-1.09367621 -2.6819824  -0.07895556]
error:  -101.9571282510044
[-1.22240964 -3.00865098 -0.12435114]
error:  -114.49117578513358
[-1.35108944 -3.33531839 -0.16969578]
error:  -127.02337819082031
[-1.47972267 -3.66198535 -0.21499494]
error:  -139.30272584799738
[-1.608315   -3.98865213 -0.26025364]
error:  -145.7168942914721
[-1.73687135 -4.31531884 -0.30547653]
error:  -147.30404646735596
[-1.86539613 -4.64198552 -0.35066793]
error:  -148.89065

/tmp/ipykernel_9223/4033946986.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


[ -52.81480766 -134.3286522   -18.21674609]
error:  -155.4244937770981
[ -52.94314099 -134.65531887  -18.26174609]
error:  -155.4244937770981
[ -53.07147433 -134.98198554  -18.30674609]
error:  -155.4244937770981
[ -53.19980766 -135.3086522   -18.35174609]
error:  -155.4244937770981
[ -53.32814099 -135.63531887  -18.39674609]
error:  -155.4244937770981
[ -53.45647433 -135.96198554  -18.44174609]
error:  -155.4244937770981
[ -53.58480766 -136.2886522   -18.48674609]
error:  -155.4244937770981
[ -53.71314099 -136.61531887  -18.53174609]
error:  -155.4244937770981
[ -53.84147433 -136.94198554  -18.57674609]
error:  -155.4244937770981
[ -53.96980766 -137.2686522   -18.62174609]
error:  -155.4244937770981
[ -54.09814099 -137.59531887  -18.66674609]
error:  -155.4244937770981
[ -54.22647433 -137.92198554  -18.71174609]
error:  -155.4244937770981
[ -54.35480766 -138.2486522   -18.75674609]
error:  -155.4244937770981
[ -54.48314099 -138.57531887  -18.80174609]
error:  -155.4244937770981
[ -54.

[-109.40980766 -278.3886522   -38.06174609]
error:  -155.4244937770981
[-109.53814099 -278.71531887  -38.10674609]
error:  -155.4244937770981
[-109.66647433 -279.04198554  -38.15174609]
error:  -155.4244937770981
[-109.79480766 -279.3686522   -38.19674609]
error:  -155.4244937770981
[-109.92314099 -279.69531887  -38.24174609]
error:  -155.4244937770981
[-110.05147433 -280.02198554  -38.28674609]
error:  -155.4244937770981
[-110.17980766 -280.3486522   -38.33174609]
error:  -155.4244937770981
[-110.30814099 -280.67531887  -38.37674609]
error:  -155.4244937770981
[-110.43647433 -281.00198554  -38.42174609]
error:  -155.4244937770981
[-110.56480766 -281.3286522   -38.46674609]
error:  -155.4244937770981
[-110.69314099 -281.65531887  -38.51174609]
error:  -155.4244937770981
[-110.82147433 -281.98198554  -38.55674609]
error:  -155.4244937770981
[-110.94980766 -282.3086522   -38.60174609]
error:  -155.4244937770981
[-111.07814099 -282.63531887  -38.64674609]
error:  -155.4244937770981
[-111.

error:  -155.4244937770981
[-172.80647433 -439.76198554  -60.29174609]
error:  -155.4244937770981
[-172.93480766 -440.0886522   -60.33674609]
error:  -155.4244937770981
[-173.06314099 -440.41531887  -60.38174609]
error:  -155.4244937770981
[-173.19147433 -440.74198554  -60.42674609]
error:  -155.4244937770981
[-173.31980766 -441.0686522   -60.47174609]
error:  -155.4244937770981
[-173.44814099 -441.39531887  -60.51674609]
error:  -155.4244937770981
[-173.57647433 -441.72198554  -60.56174609]
error:  -155.4244937770981
[-173.70480766 -442.0486522   -60.60674609]
error:  -155.4244937770981
[-173.83314099 -442.37531887  -60.65174609]
error:  -155.4244937770981
[-173.96147433 -442.70198554  -60.69674609]
error:  -155.4244937770981
[-174.08980766 -443.0286522   -60.74174609]
error:  -155.4244937770981
[-174.21814099 -443.35531887  -60.78674609]
error:  -155.4244937770981
[-174.34647433 -443.68198554  -60.83174609]
error:  -155.4244937770981
[-174.47480766 -444.0086522   -60.87674609]
error:

[-235.30480766 -598.8486522   -82.20674609]
error:  -155.4244937770981
[-235.43314099 -599.17531887  -82.25174609]
error:  -155.4244937770981
[-235.56147433 -599.50198554  -82.29674609]
error:  -155.4244937770981
[-235.68980766 -599.8286522   -82.34174609]
error:  -155.4244937770981
[-235.81814099 -600.15531887  -82.38674609]
error:  -155.4244937770981
[-235.94647433 -600.48198554  -82.43174609]
error:  -155.4244937770981
[-236.07480766 -600.8086522   -82.47674609]
error:  -155.4244937770981
[-236.20314099 -601.13531887  -82.52174609]
error:  -155.4244937770981
[-236.33147433 -601.46198554  -82.56674609]
error:  -155.4244937770981
[-236.45980766 -601.7886522   -82.61174609]
error:  -155.4244937770981
[-236.58814099 -602.11531887  -82.65674609]
error:  -155.4244937770981
[-236.71647433 -602.44198554  -82.70174609]
error:  -155.4244937770981
[-236.84480766 -602.7686522   -82.74674609]
error:  -155.4244937770981
[-236.97314099 -603.09531887  -82.79174609]
error:  -155.4244937770981
[-237.

[-295.87814099 -753.03531887 -103.44674609]
error:  -155.4244937770981
[-296.00647433 -753.36198554 -103.49174609]
error:  -155.4244937770981
[-296.13480766 -753.6886522  -103.53674609]
error:  -155.4244937770981
[-296.26314099 -754.01531887 -103.58174609]
error:  -155.4244937770981
[-296.39147433 -754.34198554 -103.62674609]
error:  -155.4244937770981
[-296.51980766 -754.6686522  -103.67174609]
error:  -155.4244937770981
[-296.64814099 -754.99531887 -103.71674609]
error:  -155.4244937770981
[-296.77647433 -755.32198554 -103.76174609]
error:  -155.4244937770981
[-296.90480766 -755.6486522  -103.80674609]
error:  -155.4244937770981
[-297.03314099 -755.97531887 -103.85174609]
error:  -155.4244937770981
[-297.16147433 -756.30198554 -103.89674609]
error:  -155.4244937770981
[-297.28980766 -756.6286522  -103.94174609]
error:  -155.4244937770981
[-297.41814099 -756.95531887 -103.98674609]
error:  -155.4244937770981
[-297.54647433 -757.28198554 -104.03174609]
error:  -155.4244937770981
[-297.

error:  -155.4244937770981
[-353.11480766 -898.7286522  -123.51674609]
error:  -155.4244937770981
[-353.24314099 -899.05531887 -123.56174609]
error:  -155.4244937770981
[-353.37147433 -899.38198554 -123.60674609]
error:  -155.4244937770981
[-353.49980766 -899.7086522  -123.65174609]
error:  -155.4244937770981
[-353.62814099 -900.03531887 -123.69674609]
error:  -155.4244937770981
[-353.75647433 -900.36198554 -123.74174609]
error:  -155.4244937770981
[-353.88480766 -900.6886522  -123.78674609]
error:  -155.4244937770981
[-354.01314099 -901.01531887 -123.83174609]
error:  -155.4244937770981
[-354.14147433 -901.34198554 -123.87674609]
error:  -155.4244937770981
[-354.26980766 -901.6686522  -123.92174609]
error:  -155.4244937770981
[-354.39814099 -901.99531887 -123.96674609]
error:  -155.4244937770981
[-354.52647433 -902.32198554 -124.01174609]
error:  -155.4244937770981
[-354.65480766 -902.6486522  -124.05674609]
error:  -155.4244937770981
[-354.78314099 -902.97531887 -124.10174609]
error:

[ -414.71480766 -1055.5286522   -145.11674609]
error:  -155.4244937770981
[ -414.84314099 -1055.85531887  -145.16174609]
error:  -155.4244937770981
[ -414.97147433 -1056.18198554  -145.20674609]
error:  -155.4244937770981
[ -415.09980766 -1056.5086522   -145.25174609]
error:  -155.4244937770981
[ -415.22814099 -1056.83531887  -145.29674609]
error:  -155.4244937770981
[ -415.35647433 -1057.16198554  -145.34174609]
error:  -155.4244937770981
[ -415.48480766 -1057.4886522   -145.38674609]
error:  -155.4244937770981
[ -415.61314099 -1057.81531887  -145.43174609]
error:  -155.4244937770981
[ -415.74147433 -1058.14198554  -145.47674609]
error:  -155.4244937770981
[ -415.86980766 -1058.4686522   -145.52174609]
error:  -155.4244937770981
[ -415.99814099 -1058.79531887  -145.56674609]
error:  -155.4244937770981
[ -416.12647433 -1059.12198554  -145.61174609]
error:  -155.4244937770981
[ -416.25480766 -1059.4486522   -145.65674609]
error:  -155.4244937770981
[ -416.38314099 -1059.77531887  -145.7

[ -478.75314099 -1218.53531887  -167.57174609]
error:  -155.4244937770981
[ -478.88147433 -1218.86198554  -167.61674609]
error:  -155.4244937770981
[ -479.00980766 -1219.1886522   -167.66174609]
error:  -155.4244937770981
[ -479.13814099 -1219.51531887  -167.70674609]
error:  -155.4244937770981
[ -479.26647433 -1219.84198554  -167.75174609]
error:  -155.4244937770981
[ -479.39480766 -1220.1686522   -167.79674609]
error:  -155.4244937770981
[ -479.52314099 -1220.49531887  -167.84174609]
error:  -155.4244937770981
[ -479.65147433 -1220.82198554  -167.88674609]
error:  -155.4244937770981
[ -479.77980766 -1221.1486522   -167.93174609]
error:  -155.4244937770981
[ -479.90814099 -1221.47531887  -167.97674609]
error:  -155.4244937770981
[ -480.03647433 -1221.80198554  -168.02174609]
error:  -155.4244937770981
[ -480.16480766 -1222.1286522   -168.06674609]
error:  -155.4244937770981
[ -480.29314099 -1222.45531887  -168.11174609]
error:  -155.4244937770981
[ -480.42147433 -1222.78198554  -168.1

error:  -155.4244937770981
[ -537.27314099 -1367.49531887  -188.09174609]
error:  -155.4244937770981
[ -537.40147433 -1367.82198554  -188.13674609]
error:  -155.4244937770981
[ -537.52980766 -1368.1486522   -188.18174609]
error:  -155.4244937770981
[ -537.65814099 -1368.47531887  -188.22674609]
error:  -155.4244937770981
[ -537.78647433 -1368.80198554  -188.27174609]
error:  -155.4244937770981
[ -537.91480766 -1369.1286522   -188.31674609]
error:  -155.4244937770981
[ -538.04314099 -1369.45531887  -188.36174609]
error:  -155.4244937770981
[ -538.17147433 -1369.78198554  -188.40674609]
error:  -155.4244937770981
[ -538.29980766 -1370.1086522   -188.45174609]
error:  -155.4244937770981
[ -538.42814099 -1370.43531887  -188.49674609]
error:  -155.4244937770981
[ -538.55647433 -1370.76198554  -188.54174609]
error:  -155.4244937770981
[ -538.68480766 -1371.0886522   -188.58674609]
error:  -155.4244937770981
[ -538.81314099 -1371.41531887  -188.63174609]
error:  -155.4244937770981
[ -538.9414

In [10]:
Y_pred = forwardprop(df.iloc[:,:-1], params)
Y_pred = np.where(Y_pred>0.5, 1, 0)
Y_pred

/tmp/ipykernel_9223/4033946986.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


array([0, 0, 0, 0, 0, 0])